### ISSUE TITLE
Can't have spaces in headers without encapsulation as string.

### ISSUE THREAD

**Issue by Schermy** [gonzalo-bulnes/dredd-rack#19]
I found that I was unable to get headers with spaces working until I had encapsulated the whole thing in a string. This was far from obvious in the documentation and it was only a great deal of trial and error that led me to find the problem.

This should either be resolved, or the documentation updated.

For example this did not work:

```
options.header "Authorization: Bearer #{token}"
```

But this did

```
options.header "'Authorization: Bearer #{token}'"
```

**Comment by gonzalo-bulnes** [comment]
Hi @Schermy!

I'll take a look at this, there must be a better way to handle these strings. Many thanks for the workaround, it a good starting point.

Regards!

**Comment by gonzalo-bulnes** [comment]
I think this issue has the same causes as #15, let's continue the conversation there please.
