### ISSUE TITLE
Rake task always throwing InvalidCommandError for local api

### ISSUE THREAD

**Issue by gottfrois** [gonzalo-bulnes/dredd-rack#26]
Tried running the following dredd rake task definition:

```ruby
Dredd::Rack::RakeTask.new do |task|
  task.runner.configure do |config|
      config.paths_to_blueprints 'apiary.apib'
      config.reporter :apiary
      config.custom ["apiaryApiKey:#{ENV['APIARY_KEY']}", "apiaryApiName:#{ENV['APIARY_NAME']}"]
      config.language :ruby
      config.level :info
      config.sorted!
  end
end
```

Result in a `InvalidCommandError` exception since the following pre-condition happens **before** the capybara server is launched and the instance variable `@api_endpoint` is setup.

https://github.com/gonzalo-bulnes/dredd-rack/blob/master/lib/dredd/rack/runner.rb#L99

**Comment by gonzalo-bulnes** [comment]
Hi @gottfrois, unless I'm wrong that's the issue described in #18, right?

**Comment by gottfrois** [comment]
Looks like it yes :)
