### ISSUE TITLE
Support Capybara 3

### ISSUE THREAD

**Issue by pilgunboris** [gonzalo-bulnes/dredd-rack#43]
Hello. Are there any plans to add support for Capybara 3.0.x ?

**Comment by pilgunboris** [comment]
@gonzalo-bulnes I see there is a PR with the fix already. When do you think you'll have time to release a new version to allow upgrading Capybara to 3.x?

**Comment by gonzalo-bulnes** [comment]
Hey, I mforgot to close this one from #46
Thank you @jesperronn! (and thank you @pilgunboris for the heads up).

**Comment by pilgunboris** [comment]
Thanks!
When do you think the new version might be released to be able to update the gem and Capybara?

**Comment by gonzalo-bulnes** [comment]
Done! @pilgunboris :wink:

**Comment by pilgunboris** [comment]
woohoo! :rocket: 
Thank you @gonzalo-bulnes!

**Comment by gonzalo-bulnes** [comment]
Thank _you_, it's really great to see you care to push on the issues and update.
